### ISSUE TITLE
大佬，看一下

### ISSUE THREAD

**Issue by ztz11** [Fedoraer/YAHO#1]
luogu用上语义分析了，我举办了一个个人邀请赛测试反作弊，废了（改了所有变量名和码风相似度为98%）

**Comment by IGhorse** [comment]
挖坟可耻啊 @ztz11

**Comment by Fedoraer** [comment]
别，别挖了，停下你的洛阳铲。
其实我也不知道语义分析的原理。

**Comment by Sunbread** [comment]
不是，你们不知道有种东西叫AST吗？
